# SonarCloud - projet PHP/Laravel (skillhub-back)
sonar.organization=nicia07
sonar.projectKey=Nicia07_skillhub-ec06

sonar.projectName=SkillHub Backend (Laravel)
sonar.sources=app,routes,config,bootstrap
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
